---
- name: Update webservers
  hosts: vb_vms
  remote_users: root

  tasks:
  - name: Ensure http is installed and updated
    ansible.builtin.yum:
        name: httpd
        state: latest
  - name: Update the apache configuration file
    ansible.builtin.template:
        src: /opt/git/devops/httpd.conf
        dest: /etc/httpd.conf
