---
- name: Update webservers
  hosts: vb_vms
  remote_user: root

  tasks:
  - name: Ensure http is installed and updated
    ansible.builtin.yum:
        name: httpd
        state: latest
  - name: Update the web site file
    ansible.builtin.template:
        src: /opt/git/devops/index.html
        dest: /var/www/html/index.html
  - name: Enable httpd service
    ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started
  - name: Disable firewalld
    ansible.builtin.service:
        name: firewalld
        enabled: no
        state: stopped